name: komodo-release-check
run-name: Check for new Komodo release

on:
  # There's no way to trigger on push to another repo, so we're going to run
  # this job periodically. If there's a new version, the build.env file will
  # be updated and pushed, which will trigger the build workflow.
  # schedule:
  #   - cron: '15 */4 * * *'

  workflow_dispatch:  

jobs:
  # This is the lightweight job that runs and decides whether to perform builds
  release-check:
    name: Komodo version check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for new version
        id: check
        uses: ./.github/actions/komodo-version-check

      - name: Update build.env and trigger workflow
        if: ${{ steps.check.outputs.should_run == 'true' }}
        shell: bash
        run: |
          sed -i "s/BUILD_VERSION=.*/BUILD_VERSION=${{ steps.check.outputs.komodo_tag }}/" .github/workflows/build.env
          
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add .github/workflows/build.env
          git commit -m "Update to ${{ steps.check.outputs.komodo_tag }}"
          git push
