name: komodo-release-check
run-name: Check for new Komodo release

on:
  # There's no way to trigger on releases in another repo, so we're polling instead
  schedule:
    - cron: '15 */4 * * *'

  workflow_dispatch:  

jobs:
  # This is the lightweight job that runs and decides whether to perform builds
  release-check:
    name: Komodo version check
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check for new version
        id: check
        uses: ./.github/actions/komodo-version-check

      - name: Load environment
        shell: bash
        run: |
          printf %s\\n "${{ steps.check.outputs.build_env }}" >> $GITHUB_ENV

      - name: Update build.env
        if: ${{ steps.check.outputs.should_run == 'true' && env.BUILD_VERSION != steps.check.outputs.komodo_tag }}
        shell: bash
        run: |
          build_env=".github/env/build.env"

          # Set current version
          sed -i "s/BUILD_VERSION=.*/BUILD_VERSION=${{ steps.check.outputs.komodo_tag }}/" "$build_env"

          # Disabled due to push limitations using GITHUB_TOKEN https://github.com/orgs/community/discussions/25702
          # (Using repository_dispatch instead)
          #
          # When we need the build workflow to run, we'll always update the build environment with a timestamp
          # so there's something to commit (allows a single trigger)
          #
          # env_update_prefix="# Updated by komodo-release-check"
          # env_update_tagline="${env_update_prefix} $(date)"
          #
          # Replace existing tagline or append to end of file if not found
          # Credit: https://superuser.com/a/976712
          # sed -i -e "
          #   /^${env_update_prefix}/{
          #     h
          #     s/.*/${env_update_tagline}/
          #   }
          #   \${
          #     x
          #     /^$/{
          #       s//\n${env_update_tagline}/
          #       H
          #     }
          #     x
          #   }" "$build_env"
          
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add "$build_env"
          if [ ! -z "$(git status --porcelain=v1 2>/dev/null)" ]; then
            git commit -m "Build ${{ steps.check.outputs.komodo_tag }}"
            git push
          fi

      - name: Trigger komodo-alpine-build
        if: ${{ steps.check.outputs.should_run == 'true' }}
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'build-trigger',
            });
