name: komodo-release-check
run-name: Check for new Komodo release

on:
  # There's no way to trigger on push to another repo, so we're going to run
  # this job periodically. If there's a new version, the build.env file will
  # be updated and pushed, which will trigger the build workflow.
  # schedule:
  #   - cron: '15 */4 * * *'

  workflow_dispatch:  

jobs:
  # This is the lightweight job that runs and decides whether to perform builds
  release-check:
    name: Komodo version check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load environment
        run: cat .github/workflows/build.env >> $GITHUB_ENV
    
      - name: Check for new version
        id: check
        shell: bash
        run: |
          # Compare our release tag with that of the official Komodo repo to see if a new build is needed
          should_run=false

          latest_komodo_release=$(curl --no-progress-meter "${GITHUB_API_URL}/repos/${KOMODO_REPO}/releases?per_page=1")
          komodo_tag=$(echo "$latest_komodo_release" | jq -r '.[0].tag_name')
          komodo_release_url=$(echo "$latest_komodo_release" | jq -r '.[0].html_url')
          
          our_tag=$(curl --no-progress-meter "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases?per_page=1" | jq -r '.[0].tag_name')

          if [[ "$our_tag" != "$komodo_tag" ]]; then
            should_run=true
          fi

          echo "Komodo tag: $komodo_tag"
          echo "Our latest tag: $our_tag"
          echo "Should run?: $should_run"

          echo "komodo_tag=${komodo_tag}" >> $GITHUB_OUTPUT
          echo "komodo_release_url=${komodo_release_url}" >> $GITHUB_OUTPUT
          echo "should_run=${should_run}" >> $GITHUB_OUTPUT

      - name: Update build.env and trigger workflow
        if: ${{ steps.check.outputs.should_run == 'true' }}
        shell: bash
        run: |
          sed -i "s/BUILD_VERSION=.*/BUILD_VERSION=${{ steps.check.outputs.komodo_tag }}/" .github/workflows/build.env
          
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add .github/workflows/build.env
          git commit -m "Update to ${{ steps.check.outputs.komodo_tag }}"
          git push
